# Site settings
title: 文风
email: yuvon1990@gmail.com
description: 个人博客-摸索版
# baseurl: "/zetsu"
# url: "http://nandomoreira.me"

author:
  name     : 'Yu Feng'
  email    : yuvon1990@gmail.com
  url      : http://windsvon.github.io/CV
  linkedin : http://cn.linkedin.com/in/yufeng90
  weibo    : http://weibo.com/yufeng90

github: https://github.com/windsvon
# disqus_shortname: "fernandomoreira"
# google_analytics: UA-52446115-1

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title

gems:
  - jekyll-paginate

collections:
  gallery:
    output: true
  # permalink: /gallery/:path/